_______ _
_______ t___

throw = False


___ countg___
    i = 0

    try:
        w.... True:
            __ throw:
                raise ZeroDivisionError()

            i += 1
            print(f'{i=}')
            t___.s..(1)
    except ZeroDivisionError:
        print('Exception occured')


__ _____ __ _____
    print('started main')

    t1 = _.T..(t.._count)
    t1.s..

    # try:
    #     t1.start()
    # except:
    #     print(f'Excepted')

    t___.s(3)

    throw = True

    ___ x __ r..(1, 5):
        print(f'{x=}')
        t___.s(1)
    print('ended main')
